INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('UserNotFound-Err', 'Kullanıcı bulunamadı.', 'TR', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('UserNotFound-Err', 'User not found.', 'EN', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('UserAlreadyExists-Err', 'Kayıtlı kullanıcı.', 'TR', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('UserAlreadyExists-Err', 'User already exists.', 'EN', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('WrongCredentials-Err', 'Giriş bilgilerinizi kontrol ediniz.', 'TR', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('WrongCredentials-Err', 'Check your credentials.', 'EN', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('SomethingWentWrong-Err', 'Geçici süre işleminizi gerçekleştiremiyoruz.', 'TR', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('SomethingWentWrong-Err', 'We are temporarily unable to process your transaction.', 'EN', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('TodoNotFound-Err', 'Todo itemi bulunamadı.', 'TR', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('TodoNotFound-Err', 'Todo item not found.', 'EN', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('TodoCouldntCreate-Err', 'Todo itemi oluşturulamadı.', 'TR', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('TodoCouldntCreate-Err', 'Todo item could not create.', 'EN', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('TodoCouldntDelete-Err', 'Todo itemi silinemedi.', 'TR', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('TodoCouldntDelete-Err', 'Todo item could not delete.', 'EN', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('TodoCouldntUpdate-Err', 'Todo itemi güncellenemedi.', 'TR', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING
INSERT INTO "Localization" (resource, message, language, created_at, updated_at, deleted_at) VALUES ('TodoCouldntUpdate-Err', 'Todo item could not update.', 'EN', CURRENT_DATE, null, null) ON CONFLICT DO NOTHING